/**
 * Las respuestas de los tres endpoints de `functions/`, con sus cabeceras.
 *
 * Existe por una razón concreta: **`public/_headers` no llega hasta aquí**. La
 * documentación de Pages es explícita —«Custom headers defined in the
 * `_headers` file are not applied to responses generated by Pages Functions»—,
 * así que todo lo que el sitio estático da por puesto (`nosniff`, la política
 * de referente, la de recursos entre orígenes) hay que escribirlo a mano en
 * cada respuesta. Repetirlo en tres archivos era garantizar que un día faltara
 * en uno: `hit.ts` ya salía sin ninguna.
 *
 * Aquí no puede entrar **ninguna** importación, por lo mismo que en
 * `contact.ts`: el bundle de la Function lo arma Wrangler por su cuenta y no
 * conoce los alias `@/` de este proyecto.
 */

/**
 * Lo que lleva toda respuesta de un endpoint, sea cual sea.
 *
 * `no-store` no es decoración: los tres responden a un `POST` con datos de
 * quien escribe, y ninguna de las tres respuestas se puede reutilizar para
 * nadie. El navegador ya lo respeta, pero entre medias hay proxies.
 */
const COMMON: Readonly<Record<string, string>> = {
  "x-content-type-options": "nosniff",
  // Un endpoint no necesita saber desde qué página se le llamó.
  "referrer-policy": "no-referrer",
  "cross-origin-resource-policy": "same-origin",
  "cache-control": "no-store",
}

function headersWith(extra: Record<string, string>): Headers {
  return new Headers({ ...COMMON, ...extra })
}

/**
 * Una respuesta JSON. El caso normal de `contact` y de `ask`.
 *
 * `extra` es para las cabeceras que sólo tienen sentido en esa respuesta: el
 * `retry-after` de un 429 o de un techo diario, y el cupo que queda.
 */
export function apiJson(
  body: unknown,
  status: number,
  extra: Record<string, string> = {},
): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: headersWith({
      "content-type": "application/json; charset=utf-8",
      ...extra,
    }),
  })
}

/**
 * Una respuesta sin cuerpo.
 *
 * `hit` contesta así siempre: al sitio no le importa si el contador está en
 * pie, y el cliente no tiene nada que hacer con la respuesta salvo ignorarla.
 */
export function apiEmpty(status: number): Response {
  return new Response(null, { status, headers: headersWith({}) })
}

/**
 * El flujo de eventos de `ask`.
 *
 * `extra` existe para las cabeceras de cupo (`x-ratelimit-remaining`), que son
 * de esta respuesta y no de todas: quien pregunta tiene derecho a saber cuántas
 * preguntas le quedan antes de chocarse con un 429, y el endpoint ya llevaba la
 * cuenta. No se mete en `COMMON` porque los otros dos endpoints no la tienen.
 */
export function apiStream(
  body: ReadableStream,
  extra: Record<string, string> = {},
): Response {
  return new Response(body, {
    headers: headersWith({
      "content-type": "text/event-stream; charset=utf-8",
      // Sin esto, un proxy intermedio puede acumular el flujo y servirlo de
      // golpe, que es exactamente lo que el streaming venía a evitar.
      "x-accel-buffering": "no",
      ...extra,
    }),
  })
}
